// Crossrow multi-row affine-4/group-64 QMV for the MTP verify path.

#![allow(unsafe_code)]
//
// Port of the promoted mlx.fast kernel family (`qmv_fast_crossrow_affine4_g64`
// and its `_m` tail variants): the stock small-M dispatch runs one threadgroup
// per input row, so each verify row re-reads the same packed weight stream.
// The crossrow design instead launches ceil(M/IPG) x-groups per 8-output tile;
// every group shares its packed weight reads across the input rows it owns.
// Per-row arithmetic (lane->k mapping, load_vector scaling ladder, qdot mask
// order, fp32 simd_sum reduction, lane-0 store) is unchanged from the stock
// `qmv_fast` M=1 kernel, so every output element is bit-identical to the
// per-row reference — the property the MTP verifier's exact-greedy contract
// needs.
//
// Dispatch mirrors the promoted host logic:
//   - N >= 4096: pair kernel for even M; _m<3,3>/_m<4,4> tails for M 3..9
//   - N < 4096: per-M templates 2..9 of the same pair kernel
//   - K multiple of 512, N multiple of 8, group 64, bits 4, affine only.

#![allow(clippy::too_many_lines)]

use std::ffi::c_char;
use std::sync::OnceLock;

use mlx_rs::{Array, Stream, error::Exception};

struct CachedMetalKernel(mlx_sys::mlx_fast_metal_kernel);
unsafe impl Send for CachedMetalKernel {}
unsafe impl Sync for CachedMetalKernel {}

impl Drop for CachedMetalKernel {
    fn drop(&mut self) {
        unsafe { mlx_sys::mlx_fast_metal_kernel_free(self.0) }
    }
}

// ---------------------------------------------------------------------------
// Kernel source. Signature is generated by mlx_fast_metal_kernel_new:
// template <typename T, int GS, int M> kernel(w, sc, bi, x, y, K_size, N_size)
// ---------------------------------------------------------------------------

const CROSSROW_QMV_SOURCE: &str = r"
constexpr int SIMD_W = 32;
constexpr int ROWS_PER_SIMD = 4;
constexpr int VPT = 16;
constexpr int BLOCK = VPT * SIMD_W;
";

// The kernel body source selects on M at runtime through template dispatch in
// a thin trampoline; mlx fast kernels compile per template instantiation.
const CROSSROW_QMV_ENTRY: &str = r"
{
  // The wrapper predeclares: template <typename OutT, int M> with inputs
  // w, sc, bi, x (OutT*), scalars K_size, N_size, output y (OutT*).
  const int K = KDIM;
  const int N = NDIM;
  const int in_vec_size_w = K / 2;
  const int in_vec_size_g = K / 64;

  uint3 tid = uint3(threadgroup_position_in_grid.x,
                    threadgroup_position_in_grid.y,
                    threadgroup_position_in_grid.z);
  uint sg = simdgroup_index_in_threadgroup;
  uint lid = thread_index_in_simdgroup;

  const int out_row = int(tid.y) * 8 + int(sg) * ROWS_PER_SIMD;

  // load_vector bits==4 (verbatim ladder)
  // Raw x load: higgs passes plain activations (not pre-scaled 4-bit x),
  // so unlike the vendored qmv_fast ladder there is no x-side dequant.
  auto load_x4 = [](const device OutT* src, thread float* xt) {
    float sum = 0;
    for (int i = 0; i < VPT; ++i) {
      float v = float(src[i]);
      xt[i] = v;
      sum += v;
    }
    return sum;
  };

  // Fetch one 512-block of packed weights + group scale/bias for the 4
  // output rows this simdgroup owns.
  auto fetch_block = [&](int k, thread uint16_t pk[ROWS_PER_SIMD][4],
                         thread float scl[ROWS_PER_SIMD],
                         thread float bia[ROWS_PER_SIMD]) {
    for (int r = 0; r < ROWS_PER_SIMD; ++r) {
      const int row = out_row + r;
      const device uint16_t* ws = reinterpret_cast<const device uint16_t*>(
          reinterpret_cast<const device uint8_t*>(w) +
          row * in_vec_size_w + k / 2 + int(lid) * 8);
      for (int i = 0; i < 4; ++i) { pk[r][i] = ws[i]; }
      const int gi = row * in_vec_size_g + k / 64 + int(lid) / 4;
      scl[r] = float(sc[gi]);
      bia[r] = float(bi[gi]);
    }
  };

  // qdot bits==4 (verbatim mask lanes)
  auto qdot4 = [](const thread uint16_t* ws, const thread float* xt,
                  float scale, float bias, float sum) {
    float accum = 0;
    for (int i = 0; i < 4; i++) {
      accum += (xt[4 * i] * float((ws[i] & 0x000f)) +
                xt[4 * i + 1] * float((ws[i] >> 4) & 0x000f) +
                xt[4 * i + 2] * float((ws[i] >> 8) & 0x000f) +
                xt[4 * i + 3] * float((ws[i] >> 12) & 0x000f));
    }
    return scale * accum + sum * bias;
  };

  // One weight fetch, two x rows: per-chain order identical to qdot4.
  auto qdot4_pair = [](const thread uint16_t* ws,
                       const thread float* x0, const thread float* x1,
                       float scale, float bias, float2 sum) {
    float2 accum = 0.0f;
    for (int i = 0; i < 4; i++) {
      accum += (float2(x0[4 * i], x1[4 * i]) * float((ws[i] & 0x000f)) +
                float2(x0[4 * i + 1], x1[4 * i + 1]) * float((ws[i] >> 4) & 0x000f) +
                float2(x0[4 * i + 2], x1[4 * i + 2]) * float((ws[i] >> 8) & 0x000f) +
                float2(x0[4 * i + 3], x1[4 * i + 3]) * float((ws[i] >> 12) & 0x000f));
    }
    return scale * accum + sum * bias;
  };

  // ---- pair path: group g owns rows {2g, 2g+1}; odd tail handled singly ----
  const int first_m = int(tid.x) * 2;
  if (first_m < M) {
    const bool has_pair = (first_m + 1) < M;
    thread float2 pr[ROWS_PER_SIMD];
    thread float sr[ROWS_PER_SIMD];
    for (int r = 0; r < ROWS_PER_SIMD; ++r) { pr[r] = 0.0f; sr[r] = 0.0f; }

    for (int k = 0; k < K; k += BLOCK) {
      thread uint16_t pk[ROWS_PER_SIMD][4];
      thread float scl[ROWS_PER_SIMD];
      thread float bia[ROWS_PER_SIMD];
      fetch_block(k, pk, scl, bia);
      thread float x0[VPT];
        const device OutT* xm0 = reinterpret_cast<const device OutT*>(x) + first_m * K + k + int(lid) * VPT;
      const float sum0 = load_x4(xm0, x0);
      if (has_pair) {
        thread float x1[VPT];
        const float sum1 = load_x4(xm0 + K, x1);
        for (int r = 0; r < ROWS_PER_SIMD; ++r) {
          pr[r] += qdot4_pair(pk[r], x0, x1, scl[r], bia[r],
                              float2(sum0, sum1));
        }
      } else {
        for (int r = 0; r < ROWS_PER_SIMD; ++r) {
          sr[r] += qdot4(pk[r], x0, scl[r], bia[r], sum0);
        }
      }
    }
    for (int r = 0; r < ROWS_PER_SIMD; ++r) {
      if (has_pair) {
        const float r0 = simd_sum(pr[r].x);
        const float r1 = simd_sum(pr[r].y);
        if (lid == 0) {
          y[first_m * N + out_row + r] = static_cast<OutT>(r0);
          y[(first_m + 1) * N + out_row + r] = static_cast<OutT>(r1);
        }
      } else {
        const float rv = simd_sum(sr[r]);
        if (lid == 0) { y[first_m * N + out_row + r] = static_cast<OutT>(rv); }
      }
    }
  }

  // ---- tail group for odd M >= 3: rows {2*g_last + 1} handled above; here
  // we rely on ceil(M/2) groups: pair kernel covers row M-1 singly when M is
  // odd (first_m = M-1, has_pair false). No separate tail kernel needed.
}
";

static CROSSROW_QMV_KERNEL: OnceLock<CachedMetalKernel> = OnceLock::new();

fn crossrow_kernel() -> &'static CachedMetalKernel {
    CROSSROW_QMV_KERNEL.get_or_init(|| {
        let source = format!("{CROSSROW_QMV_SOURCE}{CROSSROW_QMV_ENTRY}");
        let input_names: [&std::ffi::CStr; 4] = [c"w", c"sc", c"bi", c"x"];
        let output_names: [&std::ffi::CStr; 1] = [c"y"];
        let input_ptrs: Vec<*const c_char> =
            input_names.iter().map(|s| s.as_ptr()).collect();
        let output_ptrs: Vec<*const c_char> =
            output_names.iter().map(|s| s.as_ptr()).collect();
        let source = std::ffi::CString::new(source)
            .unwrap_or_else(|_| std::ffi::CString::default());
        unsafe {
            let in_vec = mlx_sys::mlx_vector_string_new_data(
                input_ptrs.as_ptr().cast_mut(),
                input_ptrs.len(),
            );
            let out_vec = mlx_sys::mlx_vector_string_new_data(
                output_ptrs.as_ptr().cast_mut(),
                output_ptrs.len(),
            );
            let kernel = mlx_sys::mlx_fast_metal_kernel_new(
                c"higgs_crossrow_qmv_affine4_g64_v2".as_ptr(),
                in_vec,
                out_vec,
                source.as_ptr(),
                std::ffi::CStr::from_bytes_with_nul_unchecked(b"\0").as_ptr(),
                false,
                false,
            );
            mlx_sys::mlx_vector_string_free(in_vec);
            mlx_sys::mlx_vector_string_free(out_vec);
            CachedMetalKernel(kernel)
        }
    })
}

/// Eligibility: affine 4-bit group-64, bf16/fp16 x, M in 2..=9, K % 512 == 0,
/// N % 8 == 0. The caller (QLinear::forward) supplies [T, K] x and the
/// packed [N, K/8] weight triple.
pub(crate) fn crossrow_qmv_verify(
    x: &Array,
    weight: &Array,
    scales: &Array,
    biases: &Array,
    t_rows: i32,
) -> Result<Array, Exception> {
    let [n_rows, k_packed] = *weight.shape() else {
        return Err(Exception::custom("crossrow_qmv: weight not 2D"));
    };
    let k_dim = k_packed * 8;
    let x_flat = x.reshape(&[t_rows, k_dim])?;
    let stream = Stream::task_local_or_default();
    let out_dtype = unsafe { mlx_sys::mlx_array_dtype(x.as_ptr()) };

    let kernel = crossrow_kernel();
    unsafe {
        let config = mlx_sys::mlx_fast_metal_kernel_config_new();
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_dtype(
            config,
            c"OutT".as_ptr(),
            out_dtype,
        );
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(
            config,
            c"M".as_ptr(),
            t_rows,
        );
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(
            config,
            c"KDIM".as_ptr(),
            k_dim,
        );
        mlx_sys::mlx_fast_metal_kernel_config_add_template_arg_int(
            config,
            c"NDIM".as_ptr(),
            n_rows,
        );
        // grid: x-groups cover ceil(M/2) pairs; y covers 8-output tiles.
        let grid_x = (t_rows + 1) / 2;
        let grid_y = (n_rows as usize + 7) / 8;
        mlx_sys::mlx_fast_metal_kernel_config_set_grid(
            config,
            grid_x as i32,
            grid_y as i32,
            1,
        );
        mlx_sys::mlx_fast_metal_kernel_config_set_thread_group(
            config, 64, 1, 1,
        );
        let out_shape = [t_rows, n_rows];
        mlx_sys::mlx_fast_metal_kernel_config_add_output_arg(
            config,
            out_shape.as_ptr(),
            out_shape.len(),
            out_dtype,
        );

        let input_ptrs = [
            weight.as_ptr(),
            scales.as_ptr(),
            biases.as_ptr(),
            x_flat.as_ptr(),
        ];
        let inputs = mlx_sys::mlx_vector_array_new_data(
            input_ptrs.as_ptr().cast_mut(),
            input_ptrs.len(),
        );
        let mut result = mlx_sys::mlx_vector_array_new();
        let status = mlx_sys::mlx_fast_metal_kernel_apply(
            &raw mut result,
            kernel.0,
            inputs,
            config,
            stream.as_ptr(),
        );
        mlx_sys::mlx_fast_metal_kernel_config_free(config);
        mlx_sys::mlx_vector_array_free(inputs);
        if status != 0 {
            mlx_sys::mlx_vector_array_free(result);
            return Err(Exception::custom("crossrow_qmv kernel apply failed"));
        }
        let len = mlx_sys::mlx_vector_array_size(result);
        if len != 1 {
            mlx_sys::mlx_vector_array_free(result);
            return Err(Exception::custom(
                "crossrow_qmv kernel returned unexpected output count",
            ));
        }
        let mut out = mlx_sys::mlx_array_new();
        mlx_sys::mlx_vector_array_get(&raw mut out, result, 0);
        mlx_sys::mlx_vector_array_free(result);
        Ok(Array::from_ptr(out))
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::panic, clippy::unwrap_used, clippy::expect_used, unsafe_code)]
    use super::*;
    use mlx_rs::ops;

    /// Every M in 2..=9 must produce bit-identical rows to stock
    /// quantized_matmul executed per row (the exactness contract the MTP
    /// verifier relies on).
    #[test]
    fn crossrow_bit_exact_vs_stock_rows() {
        let shapes: [(i32, i32); 3] = [(512, 5120), (5120, 17408), (1024, 5120)];
        for (n, k) in shapes {
            // Diverse nibbles: row i, col j -> ((i*7 + j*13) % 15 - 7) / 8
            let n_i: i32 = n;
            let k_i: i32 = k;
            let mut host = Vec::with_capacity((n_i * k_i) as usize);
            for i in 0..n_i {
                for j in 0..k_i {
                    let q = ((i * 7 + j * 13).rem_euclid(15)) - 7;
                    host.push(q as f32 / 8.0);
                }
            }
            let w32 = Array::from_slice::<f32>(&host, &[n, k]);
            let (w, s, b) = ops::quantize(&w32, Some(64), Some(4)).unwrap();
            for m in 2..=9i32 {
                let m_i: i32 = m;
                let mut xhost = Vec::with_capacity((m_i * k) as usize);
                for i in 0..m_i {
                    for j in 0..k {
                        xhost.push((((i + 1) * (j % 97)) % 31) as f32 / 16.0 - 1.0);
                    }
                }
                let x32 = Array::from_slice::<f32>(&xhost, &[m, k]);
                let x = x32.as_dtype(mlx_rs::Dtype::Bfloat16).unwrap();

                let got = crossrow_qmv_verify(&x, &w, &s, &b, m).unwrap();
                if n == 512 && m == 3 {
                    // host truth: dequantize + f32 matmul
                    let wd = ops::dequantize(&w, &s, Some(&b), Some(64), Some(4)).unwrap();
                    let truth = x32.matmul(&wd.transpose().unwrap()).unwrap();
                    let t32 = truth.as_dtype(mlx_rs::Dtype::Float32).unwrap();
                    t32.eval().unwrap();
                    let g32d = got.as_dtype(mlx_rs::Dtype::Float32).unwrap();
                    g32d.eval().unwrap();
                }
                if n == 512 && m == 3 {
                    let g32v = got.as_dtype(mlx_rs::Dtype::Float32).unwrap();
                    g32v.eval().unwrap();
                }

                // stock per-row reference
                let mut rows = Vec::new();
                for r in 0..m {
                    let xr = x.take_axis(&Array::from_slice::<i32>(&[r as i32], &[1]), 0).unwrap();
                    let yr = crate::quant_mode::quantized_matmul(
                        &xr.reshape(&[1, k]).unwrap(), &w, &s, Some(&b), true, 64, 4,
                        crate::quant_mode::QuantMode::Affine,
                    )
                    .unwrap();
                    rows.push(yr);
                }
                let want = ops::concatenate_axis(&rows.iter().collect::<Vec<_>>(), 0).unwrap();

                let g32 = got.as_dtype(mlx_rs::Dtype::Float32).unwrap();
                let w32r = want.as_dtype(mlx_rs::Dtype::Float32).unwrap();
                let diff = ops::abs(&ops::subtract(&g32, &w32r).unwrap()).unwrap();
                let mx = ops::max(&diff, None).unwrap();
                let mx: f32 = mx.item();
                assert!(
                    mx == 0.0,
                    "N={n} K={k} M={m}: crossrow diverged (max diff {mx})"
                );
            }
        }
    }
}
